// /styles/taskboardStyles.ts
const taskboardStyles = (darkMode: boolean) => ({
  app: {
    fontFamily:
      '"Inter", system-ui, -apple-system, BlinkMacSystemFont, sans-serif',
    color: "var(--text-color)",
    backgroundColor: "var(--bg-color)",
    minHeight: "100vh",
    display: "flex",
    flexDirection: "column" as const,
  },
  header: {
    padding: "16px 40px",
    backgroundColor: "var(--header-bg)",
    boxShadow: "0 1px 3px rgba(0,0,0,0.1)",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    position: "sticky" as const,
    top: 0,
    zIndex: 100,
  },
  logo: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    color: darkMode ? "#f1f1f1" : "#111827",
    fontWeight: 700,
    fontSize: "24px",
    textDecoration: "none",
  },
  logoIcon: {
    color: "#4f46e5",
    fontSize: "28px",
  },
  nav: {
    display: "flex",
    gap: "32px",
  },
  navItem: {
    color: darkMode ? "#d1d5db" : "#4b5563",
    textDecoration: "none",
    fontSize: "14px",
    fontWeight: 500,
    transition: "color 0.2s",
    padding: "8px 0",
    position: "relative" as const,
    cursor: "pointer",
  },
  activeNavItem: {
    color: "#4f46e5",
  },
  activeNavIndicator: {
    position: "absolute" as const,
    bottom: 0,
    left: 0,
    right: 0,
    height: "2px",
    backgroundColor: "#4f46e5",
    borderRadius: "2px",
  },
  headerActions: {
    display: "flex",
    alignItems: "center",
    gap: "16px",
  },
  themeToggle: {
    background: "none",
    border: "none",
    color: darkMode ? "#d1d5db" : "#4b5563",
    fontSize: "20px",
    cursor: "pointer",
    padding: "8px",
    borderRadius: "50%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    transition: "background-color 0.2s",
  },
  avatar: {
    width: "32px",
    height: "32px",
    borderRadius: "50%",
    backgroundColor: "#4f46e5",
    color: "white",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontWeight: 600,
    fontSize: "14px",
    cursor: "pointer",
  },
  main: {
    flex: 1,
    padding: "40px 24px",
    maxWidth: "1400px",
    margin: "0 auto",
    width: "100%",
  },
  pageHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "32px",
  },
  pageTitle: {
    fontSize: "28px",
    fontWeight: "700",
    margin: "0",
    color: darkMode ? "#f1f1f1" : "#111827",
    letterSpacing: "-0.025em",
  },
  actionButton: {
    backgroundColor: "#4f46e5",
    color: "white",
    border: "none",
    borderRadius: "8px",
    padding: "10px 18px",
    fontSize: "14px",
    fontWeight: "500",
    cursor: "pointer",
    transition: "all 0.2s ease",
    display: "flex",
    alignItems: "center",
    gap: "8px",
    boxShadow: "0 1px 2px rgba(0,0,0,0.05)",
  },
  toolbar: {
    display: "flex",
    justifyContent: "space-between",
    marginBottom: "24px",
    gap: "16px",
    flexWrap: "wrap" as const,
    backgroundColor: "var(--card-bg)",
    padding: "16px 20px",
    borderRadius: "10px",
    boxShadow: "0 1px 3px rgba(0,0,0,0.05)",
  },
  filters: {
    display: "flex",
    gap: "16px",
    alignItems: "center",
    flexWrap: "wrap" as const,
  },
  filterLabel: {
    fontSize: "14px",
    fontWeight: "500",
    color: darkMode ? "#d1d5db" : "#6b7280",
  },
  select: {
    padding: "8px 12px",
    borderRadius: "8px",
    border: "1px solid var(--border-color)",
    backgroundColor: "var(--card-bg)",
    color: "var(--text-color)",
    fontSize: "14px",
    fontFamily: "inherit",
    cursor: "pointer",
    transition: "border-color 0.2s, box-shadow 0.2s",
    boxShadow: "0 1px 2px rgba(0,0,0,0.02)",
    appearance: "none" as const,
    backgroundImage: `url("data:image/svg+xml;charset=UTF-8,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' fill='none' stroke='${
      darkMode ? "%23aaa" : "%23666"
    }' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'%3e%3cpolyline points='6 9 12 15 18 9'%3e%3c/polyline%3e%3c/svg%3e")`,
    backgroundRepeat: "no-repeat",
    backgroundPosition: "right 8px center",
    backgroundSize: "16px",
    paddingRight: "32px",
  },
  searchInput: {
    padding: "10px 14px",
    borderRadius: "8px",
    border: "1px solid var(--border-color)",
    backgroundColor: "var(--card-bg)",
    color: "var(--text-color)",
    fontSize: "14px",
    width: "250px",
    fontFamily: "inherit",
    transition: "border-color 0.2s, box-shadow 0.2s",
    boxShadow: "0 1px 2px rgba(0,0,0,0.02)",
  },
  addTaskContainer: {
    backgroundColor: "var(--card-bg)",
    padding: "24px",
    borderRadius: "12px",
    boxShadow: "0 4px 6px rgba(0,0,0,0.05)",
    marginBottom: "32px",
    border: "1px solid var(--border-color)",
  },
  formTitle: {
    fontSize: "18px",
    fontWeight: "600",
    margin: "0 0 20px 0",
    color: darkMode ? "#f1f1f1" : "#111827",
  },
  formGroup: {
    marginBottom: "16px",
  },
  formRow: {
    display: "flex",
    gap: "16px",
    marginBottom: "16px",
  },
  formRowItem: {
    flex: 1,
  },
  label: {
    display: "block",
    marginBottom: "6px",
    fontSize: "14px",
    color: darkMode ? "#d1d5db" : "#4b5563",
    fontWeight: "500",
  },
  input: {
    width: "100%",
    padding: "10px 14px",
    borderRadius: "6px",
    border: "1px solid var(--border-color)",
    backgroundColor: "var(--card-bg)",
    color: "var(--text-color)",
    fontSize: "14px",
    fontFamily: "inherit",
  },
  textarea: {
    width: "100%",
    padding: "10px 14px",
    borderRadius: "6px",
    border: "1px solid var(--border-color)",
    backgroundColor: "var(--card-bg)",
    color: "var(--text-color)",
    fontSize: "14px",
    fontFamily: "inherit",
    resize: "vertical" as const,
    minHeight: "80px",
  },
  formActions: {
    display: "flex",
    justifyContent: "flex-end",
    gap: "12px",
    marginTop: "20px",
  },
  cancelButton: {
    padding: "10px 18px",
    borderRadius: "6px",
    backgroundColor: "transparent",
    color: darkMode ? "#d1d5db" : "#4b5563",
    border: "1px solid var(--border-color)",
    fontSize: "14px",
    fontWeight: "500",
    cursor: "pointer",
    transition: "all 0.2s",
  },
  submitButton: {
    padding: "10px 18px",
    borderRadius: "6px",
    backgroundColor: "#4f46e5",
    color: "white",
    border: "none",
    fontSize: "14px",
    fontWeight: "500",
    cursor: "pointer",
    transition: "all 0.2s",
  },
  columnsContainer: {
    display: "grid",
    gridTemplateColumns: "repeat(3, 1fr)",
    gap: "24px",
    minHeight: "500px",
  },
  column: {
    backgroundColor: "var(--card-bg)",
    borderRadius: "12px",
    padding: "0",
    boxShadow: "0 4px 6px rgba(0,0,0,0.05)",
    height: "fit-content",
    minHeight: "400px",
    maxHeight: "calc(100vh - 300px)",
    overflowY: "auto" as const,
    border: "1px solid var(--border-color)",
    position: "relative" as const,
  },
  columnHeader: {
    fontSize: "16px",
    fontWeight: "600",
    marginBottom: "0",
    paddingBottom: "16px",
    borderBottom: "2px solid var(--border-color)",
    display: "flex",
    alignItems: "center",
    gap: "8px",
    position: "sticky" as const,
    top: "0",
    backgroundColor: "var(--card-bg)",
    zIndex: "10",
    width: "100%",
    padding: "20px 20px 16px 20px",
    borderTopLeftRadius: "12px",
    borderTopRightRadius: "12px",
  },
  columnContent: {
    padding: "0 20px 20px 20px",
  },
  todoColumn: {
    borderTop: "4px solid #3b82f6",
  },
  inProgressColumn: {
    borderTop: "4px solid #f59e0b",
  },
  doneColumn: {
    borderTop: "4px solid #10b981",
  },
  taskCard: {
    backgroundColor: "var(--card-bg)",
    borderRadius: "8px",
    padding: "16px",
    marginBottom: "16px",
    boxShadow: "0 2px 4px rgba(0,0,0,0.05)",
    border: "1px solid var(--border-color)",
    transition: "all 0.2s ease",
    cursor: "grab",
  },
  taskTitle: {
    margin: "0 0 8px 0",
    fontSize: "15px",
    fontWeight: "600",
    color: darkMode ? "#f1f1f1" : "#1f2937",
    wordBreak: "break-word" as const,
  },
  taskDescription: {
    margin: "0 0 16px 0",
    fontSize: "14px",
    color: darkMode ? "#d1d5db" : "#4b5563",
    wordBreak: "break-word" as const,
    lineHeight: "1.5",
  },
  taskMeta: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "12px",
    fontSize: "12px",
    color: darkMode ? "#9ca3af" : "#6b7280",
  },
  taskTags: {
    display: "flex",
    flexWrap: "wrap" as const,
    gap: "8px",
    marginBottom: "16px",
  },
  priorityTag: {
    padding: "4px 8px",
    borderRadius: "4px",
    fontSize: "12px",
    fontWeight: "500",
    display: "inline-flex",
    alignItems: "center",
    gap: "4px",
    backgroundColor: "transparent",
    color: "inherit",
  },
  dueDateTag: {
    padding: "4px 8px",
    borderRadius: "4px",
    fontSize: "12px",
    fontWeight: "500",
    backgroundColor: darkMode ? "#374151" : "#f3f4f6",
    color: "inherit",
    display: "inline-flex",
    alignItems: "center",
    gap: "4px",
  },
  assigneeTag: {
    padding: "4px 8px",
    borderRadius: "4px",
    fontSize: "12px",
    fontWeight: "500",
    backgroundColor: darkMode ? "#374151" : "#f3f4f6",
    color: "inherit",
    display: "inline-flex",
    alignItems: "center",
    gap: "4px",
  },
  taskActions: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    borderTop: "1px solid var(--border-color)",
    marginTop: "12px",
    paddingTop: "12px",
  },
  taskActionButtons: {
    display: "flex",
    gap: "8px",
  },
  iconButton: {
    backgroundColor: darkMode ? "#374151" : "#f3f4f6",
    border: "none",
    borderRadius: "6px",
    padding: "6px",
    cursor: "pointer",
    transition: "all 0.2s ease",
    fontSize: "13px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: darkMode ? "#d1d5db" : "#4b5563",
    width: "28px",
    height: "28px",
  },
  moveButtons: {
    display: "flex",
    gap: "8px",
  },
  disabledButton: {
    backgroundColor: darkMode ? "#2d2d2d" : "#f9fafb",
    border: "none",
    borderRadius: "6px",
    padding: "6px",
    color: darkMode ? "#4b5563" : "#d1d5db",
    cursor: "not-allowed",
    fontSize: "13px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: "28px",
    height: "28px",
  },
  emptyState: {
    textAlign: "center" as const,
    color: darkMode ? "#9ca3af" : "#9ca3af",
    padding: "24px 16px",
    fontSize: "14px",
    backgroundColor: darkMode ? "#2d2d2d" : "#f9fafb",
    borderRadius: "8px",
    border: "1px dashed var(--border-color)",
  },
  statusIndicator: {
    display: "inline-block",
    width: "8px",
    height: "8px",
    borderRadius: "50%",
    marginRight: "8px",
  },
  todoIndicator: {
    backgroundColor: "#3b82f6",
  },
  inProgressIndicator: {
    backgroundColor: "#f59e0b",
  },
  doneIndicator: {
    backgroundColor: "#10b981",
  },
  taskCount: {
    backgroundColor: darkMode ? "#374151" : "#e5e7eb",
    color: darkMode ? "#d1d5db" : "#4b5563",
    fontSize: "13px",
    fontWeight: "500",
    padding: "2px 8px",
    borderRadius: "9999px",
    marginLeft: "auto",
  },
  modal: {
    position: "fixed" as const,
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 1000,
  },
  modalContent: {
    backgroundColor: "var(--card-bg)",
    borderRadius: "12px",
    padding: "24px",
    boxShadow: "0 4px 6px rgba(0,0,0,0.1)",
    maxWidth: "600px",
    width: "90%",
    maxHeight: "90vh",
    overflowY: "auto" as const,
  },
  modalHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "20px",
  },
  modalTitle: {
    margin: 0,
    fontSize: "20px",
    fontWeight: "600",
    color: darkMode ? "#f1f1f1" : "#111827",
  },
  closeButton: {
    background: "none",
    border: "none",
    color: darkMode ? "#9ca3af" : "#6b7280",
    fontSize: "24px",
    cursor: "pointer",
    padding: "4px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  footer: {
    backgroundColor: "var(--footer-bg)",
    padding: "32px 40px",
    borderTop: "1px solid var(--border-color)",
  },
  footerContent: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    maxWidth: "1400px",
    margin: "0 auto",
    flexWrap: "wrap" as const,
    gap: "20px",
  },
  footerLinks: {
    display: "flex",
    gap: "24px",
  },
  footerLink: {
    color: darkMode ? "#9ca3af" : "#6b7280",
    textDecoration: "none",
    fontSize: "14px",
    transition: "color 0.2s",
    cursor: "pointer",
  },
  copyright: {
    color: darkMode ? "#9ca3af" : "#6b7280",
    fontSize: "14px",
  },
  toast: {
    position: "fixed" as const,
    bottom: "24px",
    right: "24px",
    padding: "12px 20px",
    borderRadius: "8px",
    boxShadow: "0 4px 12px rgba(0, 0, 0, 0.15)",
    display: "flex",
    alignItems: "center",
    gap: "12px",
    maxWidth: "400px",
    zIndex: 1000,
    transition: "transform 0.3s ease, opacity 0.3s ease",
    opacity: 1,
    transform: "translateY(0)",
    pointerEvents: "all" as React.CSSProperties["pointerEvents"],
  },
  toastInfo: {
    backgroundColor: darkMode ? "#1e3a8a" : "#dbeafe",
    color: darkMode ? "#dbeafe" : "#1e3a8a",
    borderLeft: "4px solid #3b82f6",
  },
  toastSuccess: {
    backgroundColor: darkMode ? "#065f46" : "#d1fae5",
    color: darkMode ? "#d1fae5" : "#065f46",
    borderLeft: "4px solid #10b981",
  },
  toastWarning: {
    backgroundColor: darkMode ? "#92400e" : "#fef3c7",
    color: darkMode ? "#fef3c7" : "#92400e",
    borderLeft: "4px solid #f59e0b",
  },
  toastError: {
    backgroundColor: darkMode ? "#7f1d1d" : "#fee2e2",
    color: darkMode ? "#fee2e2" : "#7f1d1d",
    borderLeft: "4px solid #ef4444",
  },
  toastMessage: {
    flex: 1,
    fontSize: "14px",
    fontWeight: 500,
  },
  toastCloseButton: {
    background: "none",
    border: "none",
    cursor: "pointer",
    fontSize: "18px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "inherit",
    opacity: 0.7,
    transition: "opacity 0.2s",
  },
  deleteModal: {
    position: "fixed" as const,
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 1000,
  },
  deleteModalContent: {
    backgroundColor: "var(--card-bg)",
    borderRadius: "12px",
    padding: "24px",
    boxShadow: "0 4px 6px rgba(0,0,0,0.1)",
    maxWidth: "500px",
    width: "90%",
  },
  deleteModalHeader: {
    marginBottom: "16px",
  },
  deleteModalTitle: {
    margin: 0,
    fontSize: "20px",
    fontWeight: "600",
    color: darkMode ? "#f1f1f1" : "#111827",
  },
  deleteModalMessage: {
    fontSize: "15px",
    marginBottom: "24px",
    color: darkMode ? "#d1d5db" : "#4b5563",
    lineHeight: "1.5",
  },
  deleteModalTaskTitle: {
    fontSize: "16px",
    fontWeight: "500",
    color: darkMode ? "#f1f1f1" : "#111827",
    padding: "12px",
    margin: "12px 0",
    backgroundColor: darkMode ? "#1a1a1a" : "#f3f4f6",
    borderRadius: "6px",
    borderLeft: "3px solid #ef4444",
  },
  deleteModalActions: {
    display: "flex",
    justifyContent: "flex-end",
    gap: "12px",
    marginTop: "20px",
  },
  cancelDeleteButton: {
    padding: "10px 18px",
    borderRadius: "6px",
    backgroundColor: "transparent",
    color: darkMode ? "#d1d5db" : "#4b5563",
    border: "1px solid var(--border-color)",
    fontSize: "14px",
    fontWeight: "500",
    cursor: "pointer",
    transition: "all 0.2s",
  },
  confirmDeleteButton: {
    padding: "10px 18px",
    borderRadius: "6px",
    backgroundColor: "#ef4444",
    color: "white",
    border: "none",
    fontSize: "14px",
    fontWeight: "500",
    cursor: "pointer",
    transition: "all 0.2s",
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },

  // Add mobile menu button styles
  hamburgerButton: {
    background: "none",
    border: "none",
    color: darkMode ? "#d1d5db" : "#4b5563",
    fontSize: "24px",
    cursor: "pointer",
    padding: "8px",
    borderRadius: "50%",
    display: "none", // Hidden by default, shown in media query
    alignItems: "center",
    justifyContent: "center",
    transition: "background-color 0.2s",
    marginRight: "8px",
  },

  // Add sidebar styles
  sidebar: {
    position: "fixed" as const,
    top: 0,
    left: 0,
    height: "100vh",
    width: "280px",
    backgroundColor: darkMode ? "#242424" : "#ffffff",
    boxShadow: "2px 0 10px rgba(0,0,0,0.1)",
    zIndex: 1000,
    transition: "transform 0.3s ease",
    display: "flex",
    flexDirection: "column" as const,
    padding: "16px",
  },

  sidebarHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "24px",
    paddingBottom: "16px",
    borderBottom: "1px solid var(--border-color)",
  },

  sidebarLogo: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    color: darkMode ? "#f1f1f1" : "#111827",
    fontWeight: 700,
    fontSize: "22px",
  },

  sidebarClose: {
    background: "none",
    border: "none",
    color: darkMode ? "#d1d5db" : "#4b5563",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },

  sidebarNav: {
    display: "flex",
    flexDirection: "column" as const,
    gap: "16px",
  },

  sidebarNavItem: {
    color: darkMode ? "#d1d5db" : "#4b5563",
    textDecoration: "none",
    fontSize: "16px",
    fontWeight: 500,
    padding: "12px 16px",
    borderRadius: "8px",
    transition: "all 0.2s",
    cursor: "pointer",
  },

  sidebarNavItemActive: {
    backgroundColor: darkMode ? "#374151" : "#f3f4f6",
    color: "#4f46e5",
  },

  sidebarOverlay: {
    position: "fixed" as const,
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    zIndex: 999,
    transition: "opacity 0.3s ease, visibility 0.3s ease",
  },

  sidebarVisible: {
    opacity: 1,
    visibility: "visible",
    transform: "translateX(0)",
  },

  sidebarHidden: {
    opacity: 0,
    visibility: "hidden",
    transform: "translateX(-100%)",
  },
  // Section styles for different views
  sectionContainer: {
    flex: 1,
    width: "100%",
  },

  placeholderSection: {
    display: "flex",
    flexDirection: "column" as const,
    alignItems: "center",
    justifyContent: "center",
    padding: "60px 24px",
    textAlign: "center" as const,
  },

  placeholderIcon: {
    fontSize: "48px",
    color: darkMode ? "#4b5563" : "#d1d5db",
    marginBottom: "24px",
  },

  placeholderTitle: {
    fontSize: "24px",
    fontWeight: 600,
    marginBottom: "16px",
    color: darkMode ? "#f1f1f1" : "#111827",
  },

  placeholderText: {
    fontSize: "16px",
    lineHeight: "1.5",
    maxWidth: "500px",
    color: darkMode ? "#9ca3af" : "#6b7280",
    marginBottom: "24px",
  },

  sidebarOpen: {
    transform: "translateX(0)",
  },

  sidebarClosed: {
    transform: "translateX(-100%)",
  },

  sidebarTitle: {
    margin: 0,
    fontSize: "18px",
    fontWeight: "600",
    color: darkMode ? "#f1f1f1" : "#111827",
  },

  sidebarLink: {
    color: darkMode ? "#d1d5db" : "#374151",
    textDecoration: "none",
    fontSize: "15px",
    padding: "8px",
    borderRadius: "6px",
    transition: "background 0.2s ease",
    cursor: "pointer",
  },
});

export default taskboardStyles;
